argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
argocd-apps:
  projects:
    - name: core
      # finalizers:
      # - resources-finalizer.argocd.argoproj.io
      # additionalAnnotations: {helm.sh/hook: "post-install"}
      description: Contains applications that are always deployed.
      destinations:
        - namespace: '*'
          server: '*'
      sourceRepos:
        - '*'
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
  applications:
    - name: root-app
      namespace: default
      # finalizers:
      # - resources-finalizer.argocd.argoproj.io
      project: core
      # additionalAnnotations: {helm.sh/hook: "post-install"}
      source:
        helm:
          valueFiles:
            - values.yaml
        repoURL: https://github.com/kannancmohan/argohelm.git
        targetRevision: HEAD
        path: charts/root-app/
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          selfHeal: true